stages:
  split:
    cmd: python src/data/data_split.py
    deps:
    - data/raw_data/
    - src/data/data_split.py
    outs:
    - data/processed_data/X_train.csv
    - data/processed_data/X_test.csv
    - data/processed_data/y_train.csv
    - data/processed_data/y_test.csv
